import type { IMediaFull } from "../services/types/media.types";

export const mediaSeed: IMediaFull[] = [
  {
    _id: "1a1f3c9b-7d44-4f1a-9c1a-001",
    tmdbId: 27205,
    title: "Inception",
    overview: "Dream infiltration.",
    posterPath: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    mediaType: "movie",
    trailerKey: "YoHD9XEInc0",
    genres: ["Action", "Sci-Fi"],
    rating: 8.8,
    popularity: 90,
    releaseDate: "2010-07-16",
    dominantColor: "#0f172a",
    runtime: 148,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2b2f3c9b-7d44-4f1a-9c1a-002",
    tmdbId: 157336,
    title: "Interstellar",
    overview: "Space exploration.",
    posterPath: "/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    mediaType: "movie",
    trailerKey: "zSWdZVtXT7E",
    genres: ["Adventure", "Drama"],
    rating: 8.6,
    popularity: 95,
    releaseDate: "2014-11-07",
    dominantColor: "#1e293b",
    runtime: 169,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3c3f3c9b-7d44-4f1a-9c1a-003",
    tmdbId: 603,
    title: "The Matrix",
    overview: "Reality is a simulation.",
    posterPath: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    mediaType: "movie",
    trailerKey: "vKQi3bBA1y8",
    genres: ["Action"],
    rating: 8.7,
    popularity: 88,
    releaseDate: "1999-03-31",
    dominantColor: "#020617",
    runtime: 136,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4d4f3c9b-7d44-4f1a-9c1a-004",
    tmdbId: 155,
    title: "The Dark Knight",
    overview: "Batman vs Joker.",
    posterPath: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    mediaType: "movie",
    trailerKey: "EXeTwQWrcwY",
    genres: ["Action"],
    rating: 9.0,
    popularity: 98,
    releaseDate: "2008-07-18",
    dominantColor: "#111827",
    runtime: 152,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5e5f3c9b-7d44-4f1a-9c1a-005",
    tmdbId: 550,
    title: "Fight Club",
    overview: "Underground fights.",
    posterPath: "/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    mediaType: "movie",
    trailerKey: "BdJKm16Co6M",
    genres: ["Drama"],
    rating: 8.8,
    popularity: 85,
    releaseDate: "1999-10-15",
    dominantColor: "#3f3f46",
    runtime: 139,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6f6f3c9b-7d44-4f1a-9c1a-006",
    tmdbId: 680,
    title: "Pulp Fiction",
    overview: "Crime stories.",
    posterPath: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    mediaType: "movie",
    trailerKey: "s7EdQ4FqbhY",
    genres: ["Crime"],
    rating: 8.9,
    popularity: 92,
    releaseDate: "1994-10-14",
    dominantColor: "#7f1d1d",
    runtime: 154,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "7g7f3c9b-7d44-4f1a-9c1a-007",
    tmdbId: 120,
    title: "LOTR: Fellowship",
    overview: "Ring journey.",
    posterPath: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    mediaType: "movie",
    trailerKey: "V75dMMIW2B4",
    genres: ["Fantasy"],
    rating: 8.8,
    popularity: 93,
    releaseDate: "2001-12-19",
    dominantColor: "#78350f",
    runtime: 178,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // TV
  {
    _id: "8h8f3c9b-7d44-4f1a-9c1a-008",
    tmdbId: 1399,
    title: "Game of Thrones",
    overview: "Iron Throne war.",
    posterPath: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    mediaType: "tv",
    trailerKey: "KPLWWIOCOOQ",
    genres: ["Fantasy"],
    rating: 9.2,
    popularity: 100,
    releaseDate: "2011-04-17",
    dominantColor: "#111827",
    endYear: 2019,
    numberOfSeasons: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "9i9f3c9b-7d44-4f1a-9c1a-009",
    tmdbId: 1396,
    title: "Breaking Bad",
    overview: "Teacher → drug lord.",
    posterPath: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    mediaType: "tv",
    trailerKey: "HhesaQXLuRY",
    genres: ["Crime"],
    rating: 9.5,
    popularity: 100,
    releaseDate: "2008-01-20",
    dominantColor: "#14532d",
    endYear: 2013,
    numberOfSeasons: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "10j10c9b-7d44-4f1a-9c1a-010",
    tmdbId: 66732,
    title: "Stranger Things",
    overview: "Supernatural mystery.",
    posterPath: "/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
    mediaType: "tv",
    trailerKey: "b9EkMc79ZSU",
    genres: ["Mystery"],
    rating: 8.7,
    popularity: 97,
    releaseDate: "2016-07-15",
    dominantColor: "#7f1d1d",
    endYear: null,
    numberOfSeasons: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "11k11c9b-7d44-4f1a-9c1a-011",
    tmdbId: 94605,
    title: "Arcane",
    overview: "League origins.",
    posterPath: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    mediaType: "tv",
    trailerKey: "fXmAurh012s",
    genres: ["Animation"],
    rating: 9.0,
    popularity: 96,
    releaseDate: "2021-11-06",
    dominantColor: "#0f172a",
    endYear: null,
    numberOfSeasons: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "12l12c9b-7d44-4f1a-9c1a-012",
    tmdbId: 82856,
    title: "The Mandalorian",
    overview: "Bounty hunter.",
    posterPath: "/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    mediaType: "tv",
    trailerKey: "aOC8E8z_ifw",
    genres: ["Sci-Fi"],
    rating: 8.8,
    popularity: 95,
    releaseDate: "2019-11-12",
    dominantColor: "#1e3a8a",
    endYear: null,
    numberOfSeasons: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "13m13c9b-7d44-4f1a-9c1a-013",
    tmdbId: 2316,
    title: "The Office",
    overview: "Office comedy.",
    posterPath: "/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    mediaType: "tv",
    trailerKey: "Vmb1tqYqyII",
    genres: ["Comedy"],
    rating: 8.9,
    popularity: 89,
    releaseDate: "2005-03-24",
    dominantColor: "#facc15",
    endYear: 2013,
    numberOfSeasons: 9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "14n14c9b-7d44-4f1a-9c1a-014",
    tmdbId: 1402,
    title: "The Walking Dead",
    overview: "Zombie survival.",
    posterPath: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    mediaType: "tv",
    trailerKey: "sfAc2U20uyg",
    genres: ["Horror"],
    rating: 8.2,
    popularity: 91,
    releaseDate: "2010-10-31",
    dominantColor: "#1f2937",
    endYear: 2022,
    numberOfSeasons: 11,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "15o15c9b-7d44-4f1a-9c1a-015",
    tmdbId: 456,
    title: "The Simpsons",
    overview: "Animated family.",
    posterPath: "/k5UALlcA0EnviaCUn2wMjOWYiOO.jpg",
    mediaType: "tv",
    trailerKey: "XPG0MqIcby8",
    genres: ["Animation"],
    rating: 8.7,
    popularity: 93,
    releaseDate: "1989-12-17",
    dominantColor: "#fbbf24",
    endYear: null,
    numberOfSeasons: 35,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
